# Site settings
title: "My Jekyll Site"
description: "A minimal Jekyll site"
baseurl: "" # If you're publishing on GitHub Pages at username.github.io, keep it blank
#url: "https://michaelscutari.com" # Update with your GitHub Pages URL or custom domain

# Collections
collections:
  engineering:
    output: true
    permalink: /projects/:title/
  film:
    output: true
    permalink: /film/:title/

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
